default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    adapter: mysql2
    host: mysql-c87bede-xmentits2-d651.h.aivencloud.com
    port: 14005
    database: defaultdb
    username: avnadmin
    password: 'AVNS_CBWQOMmPcasiNYg8y0c'
    sslverify: false
    encoding: utf8
    pool: 5
    timeout: 5000

  cache:
    adapter: mysql2
    host: mysql-c87bede-xmentits2-d651.h.aivencloud.com
    port: 14005
    database: defaultdb
    username: avnadmin
    password: 'AVNS_CBWQOMmPcasiNYg8y0c'
    sslverify: false
    encoding: utf8
    pool: 5
    timeout: 5000

  queue:
    adapter: mysql2
    host: mysql-c87bede-xmentits2-d651.h.aivencloud.com
    port: 14005
    database: defaultdb
    username: avnadmin
    password: 'AVNS_CBWQOMmPcasiNYg8y0c'
    sslverify: false
    encoding: utf8
    pool: 5
    timeout: 5000

  cable:
    adapter: mysql2
    host: mysql-c87bede-xmentits2-d651.h.aivencloud.com
    port: 14005
    database: cable_production # Create this database or use a different one for cable
    username: avnadmin
    password: 'AVNS_CBWQOMmPcasiNYg8y0c'
    sslverify: false
    encoding: utf8
    pool: 5
    timeout: 5000
